# Generated by Django 3.2.10 on 2022-03-21 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_order_test_product_image_shippingaddress_review_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
