# Generated by Django 3.2.10 on 2022-04-09 09:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_useraccount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAccount',
            new_name='Account',
        ),
    ]
